name: valgrind leak check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: |
        sudo apt-get install -y libssl-dev valgrind
    
    - name: make re/rem
      run: |
        git clone https://github.com/baresip/re.git
        git clone https://github.com/creytiv/rem.git
        for p in re rem; do cd $p && sudo PATH="$PATH" make install && cd - && sudo rm -Rf $p; done
        sudo ldconfig

    - name: make baresip selftest
      run: make EXTRA_CFLAGS="-Werror" CCACHE= test;

    - name: valgrind test
      run: valgrind --leak-check=full --show-reachable=yes --error-exitcode=42 ./selftest 
